# Generated by Django 4.2.4 on 2024-05-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_imagelikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageLikes',
        ),
    ]
