# Generated by Django 4.2.4 on 2024-05-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_imagelikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelikes',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='photos.image'),
        ),
    ]
